eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator: enable
      routes:
        - id: post-service
          uri: http://localhost:8082
          predicates:
            - Path=/post-service/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user-service/**
server:
  port: 8221

